name: audit-for-vulnerabilities
run-name: ${{ github.actor }} is auditing packages
# based on previous action outline and ashlyn's reccommendations/examples.

on:
  push:
    paths:
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: write

jobs:
  audit-and-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Display vulnerabilities
        run: npm audit || true
        # showing vulnerable stuff before the fix happens, or else we might not see it. Please dont remove.
      - name: Run audit fix
        run: npm audit fix
      # fix all the bad stuff!!
